apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-api
  labels:
    app: treetracker-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-api
  template:
    metadata:
      labels:
        app: treetracker-api
    spec:
      containers:
        - name: treetracker-api
          image: greenstand/treetracker-api:VERSION
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: treetracker-database-connection
                  key: db
            - name: DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: treetracker-database-connection
                  key: schema
            - name: NODE_LOG_LEVEL
              value: trace
            - name: REMOTE_LOG_URL
              value: http://104.131.78.177:8000
            - name: RABBIT_MQ_URL
              valueFrom:
                secretKeyRef:
                  name: treetracker-rabbitmq-connection
                  key: messageQueue
