apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: treetracker-api
spec:
  encryptedData:
    db: AgDG7NtZQRRHE8X1gWZeBunF1LMRXE0DZRH8I8QXb0brvnuH33ey4QiZ43vOP4veSI9HoFP7bpPOnru+weq7T46LY+QcHdW/Pfy8lD1oNXtTcjvkLeWZDBdPIgqzFGVfylx0V8uRCwwXd/mcH2M8YQYD0OvJxaBQj+93a9LfvnGqvSPjmepQ2VIMCoi4CJY/jg6ToMCnZIVjvjXXBNuEfFbBOOCdT4h4gzzDd+A/lmqp3vaH+85Wx9D/00CFxrt1o8uzHQPhnZziuwlgjyFifjKyWWsE3nrQPXygBcyMhGnchYqdPrcfamtacSry2fZGgfNMyJQ+LZMqxuQqne0Zfk3+/y/LTACOXPhB8SC5Y151j4KGU5iIFUOC5v9CbE3m69KKOGheuwkaG7UXqsDvWSNS+G4TjuS6oFSnh8vZ9DQOh8nh2uvMybVflmQWgHi/zMK3O4WdyZyKSFUu8EjWneTD8pgl5WQyHiPsYcB2wkN1ZlevCLXXp+r0vMfVE5PpY/Q7O/YvBwQd/j+6jJimxeH0JJR3eoq+cp1kWN46JENPM6qxOKzd5LZoy902F6mr9WSB4rI3r86/959vtuK23zBLH3eDrgM856kx1EubFJIW7OYFhkoNmkroNYwEl8LQWQxnuLgTH9NxTDUImif4QSl2SuUIAlFjbb9uYs5ZlR44M3pT7rfY2rdwovYkYvI6BMceFULzO4DN5Fzz/xTVoJwmalyBcuQdxmVHVc2OP0AvDwIWYVlSJ37WFAM4wlwThjqV+QWgxS8+newiNPcjB0usHb6bxGFNDBcgD1NPzfPyY95WagV4sF+Kfr2pY0zeCEiRtSeR8yiDOh5VdiRMGUIH5WyIl2abA5pZpmeWzNnBTNJWNOnPdrM=
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: treetracker-api

