bases:
  - ../../base
patchesStrategicMerge:
  - database-connection-sealed-secret.yaml
  - database-migration-connection-sealed-secret.yaml
  - deployment.yaml
  - mapping.yaml
  - rabbitmq-connection-sealed-secret.yaml
