patchesStrategicMerge:
- database-connection-sealed-secret.yaml
- database-migration-connection-sealed-secret.yaml
- deployment.yaml
- mapping.yaml
- rabbitmq-connection-sealed-secret.yaml
images:
- name: greenstand/treetracker-api
  newTag: 1.22.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
