apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-api
spec:
  prefix: /treetracker/
  service: treetracker-api
  rewrite: /
  cors:
    origins: "*"
    methods: GET
    headers: Content-Type
