apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: treetracker-api
spec:
  encryptedData:
    db: AgBAl8RXzxKq7rWy9+3FPWU3KFVMFVTWoplnlnudd1FFtfglKZzQnJhQ8RHPy/Wv/Y91fC1fR8ixuBpYz1gQF0afKJHkU9pu88rCi/G4zuRa620R8YhrXh7g2o2Ht3NNoEvOoRr93ksL9TAKtCgD7WlmX76ex5mQTVEdPyAnyiCvG0XPLMSq4zzP1DVGIrscTOR4Yq9LCxbLx2fwBWR23ZBf/Y1EwKLexHEtr6yzCxKp84wrDDJCCvEnz10fg/cY5k1BIi3uRnIxBLtBjlBywNmrHiGHeQxK9A5q0X5R64flO+JBVPHv80NulS+tfGMMszTjYLdOvGqSmUpOuycyq2psfHCvmyw9rA0P/XI5ybQlQQkpK6iAJDIXfedPRRmfIWrIwOf0CoM2NG2pQpPBDUj6oUyy/GTSH+VayBYfzY5w3E0OZpRlHSeYhrEVyytnmxYA4FuhqhtuuihBivO9nFdUhldCpECMwFUrTIx1i/K5T7t6xFM7s8cFKAwhk1t6CqwglvHuAPK7r0Y2H1+Y46AHET8gnw3qLjgR2l09BoND3CEtclHJtRg0KtDIUEHn9+0VCXKeDP4fIU2pV0eoM/9TTcXlMJkgH/Bg4c07nTR5K6NTia79MGRM6b5Eb2Fl/tdJ6FWL5chFaAGSWhSy74HVBJV5mQZYW1et6l5Epe0KrFVdYzGMcgDzGQs+5x520j7E6ktBCSvgTeboQyhkxcmwj1NyStPhT9PpqBlOuTtqsry5cgE31pWKF8GUdiBJaaeLipOqwqrgM+2uzFbzTvLYmcTqkXJhnR/9jL0R0j4nhjnZhy7BFkWqUuTpssvtEMixUi9kVrNDwekQodqTSuV+7fAn6pzTdT63z04CyjQSypToLyHxSaY=
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: treetracker-api
